;; Auto generated by `pyim-generate-dict-cache-file', don't edit it by hand!

#s(hash-table size 1000000 test equal rehash-size 1.5 rehash-threshold 0.8 data ("chu" ("出" "处") "c" ("从" "成" "次" "错" "出" "重" "串" "处") "jin" ("今") "j" ("救" "及" "将" "键" "就" "见" "今" "即" "减" "机" ...) "zhong" ("中" "重") "z" ("照" "装" "中" "在" "字" "这" "再" "最" "指" "则" ...) "guo" ("国") "g" ("个" "跟" "够" "该" "给" "各" "国") "zhong-guo" ("中国") "z-g" ("这个" "足够" "中国") ...))
