;; Auto generated by `pyim-generate-dict-cache-file', don't edit it by hand!

#s(hash-table size 1000000 test equal rehash-size 1.5 rehash-threshold 0.8 data ("今天" (:count 5) "天气" (:count 2) "很好" (:count 2) "老婆" (:count 4) "快捷" (:count 2) "梁礼华" (:count 2) "喂奶" (:count 2)))
